### ISSUE TITLE
taskwiki turns out built-in markdown folding

### ISSUE THREAD

**Issue by nocibambi** [tools-life/taskwiki#283]
I use markdown header folding in normal files (i.e. not vimwiki files) with the built-in `leg g:markdown_folding = 1` setting. Unfortunately installing taskwiki turns this off.

A minimal viable vimrc:

```vimrc
""" Markdown folding
let g:markdown_folding = 1
let g:vimwiki_folding = 'expr'
 
 
""" Plugins
call plug#begin('~/.vim/plugged')
 
" Vimwiki
Plug 'vimwiki/vimwiki'
 
" taskwiki   
Plug 'tbabej/taskwiki'
 
call plug#end()

 
""" Vimwiki settings
set nocompatible
filetype plugin on
syntax on
~
```

I tried out commenting out taskwiki folding [as mentioned here](https://github.com/tools-life/taskwiki/issues/147#issuecomment-308674963) but that did not help.

Commenting out the taskwiki plugin turns the markdown folding back.

I am on Ubuntu 18.04 and NVIM v0.4.3.

Is there an easy solution to this?

**Comment by liskin** [comment]
```vim
let g:vimwiki_global_ext = 0
```

See https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/doc/vimwiki.txt#L2082

**Comment by tbabej** [comment]
Closing as resolved.
