### ISSUE TITLE
Viewports does not work anymore?

### ISSUE THREAD

**Issue by sjohnsen** [tools-life/taskwiki#308]
When I create a viewport in vimwiki it will not show any tasks when I save.
I has been working before, but not after recent upgrade.
Currently on master, tasklib 2.2.1, taskwarrior 2.5.1, and devel branch of vimwiki.

I use markdown as syntax in vimwiki

**Comment by tbabej** [comment]
Hi @sjohnsen!

Viewports definitely still work, they are part of our test suitecase. Can you post a minimal example file that is not working for you?

**Comment by sjohnsen** [comment]
```
== Todo work | +work ==
```

None of the ones I have tried work now. This is the simplest one, and one I am pretty sure worked before.
Also my existing Viewports does not update correctly. If I add a task under a viewport it does not inherit the filter.

[CR] on a viewport does not work, but [CR] on a task is working as intended.

**Comment by liskin** [comment]
@sjohnsen Can you make it work if you downgrade to 7a2b9d9 (whatever that is; it's not a commit in the taskwiki repo)? If yes, can you do a bisect? Because I have to admit I have absolutely no idea what could cause this. I would have guessed it's not getting loaded at all but if [CR] on a task works... then I'm lost.

Also, what version of vim do you use?

**Comment by sjohnsen** [comment]
Sorry the commit had a typo, I meant: 7a2b0d9
Version of vim is 8.2 (From Fedora 32)

Just did a downgrade (git checkout 7a2b0d9) of taskwiki, and Viewports works correctly.
Then I went up the commit-log untill it stopped working.

Seems like commit "7b67d51 cache: Get markup_syntax from vimwiki, drop g:taskwiki_markup_syntax" is introducing this behavior.

I do not have `let g:taskwiki_markup_syntax` in my .vimrc,  but I have syntax set to markdown in vimwiki_list in my .vimrc.

**Comment by liskin** [comment]
Oh, right, you're using "default" markup headers in "markdown" files. That's a unusual. I'm guessing the syntax highlighting isn't working very well either, is it? I'm not sure this combination is worth supporting. Technically speaking we can reintroduce the `g:taskwiki_markup_syntax` variable to let users configure this, but it's just weird.  Would you be willing to rewrite the headers to markdown? Or keep a local patch that hardcodes https://github.com/tools-life/taskwiki/commit/7b67d510cc8d7a4648e48ac993baf98be8d73939#diff-73dda03347f333c77ccf1344318512f3R111 to `"default"`?

**Comment by sjohnsen** [comment]
Now I feel stupid, I just have to use markdown headers....

**Comment by tbabej** [comment]
@sjohnsen no reason to feel stupid, it's always better to raise an issue in case you encounter a real bug! Happy you managed to work this one out (and thanks to @liskin for the help with debugging).
