### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by rhaynes74** [tools-life/taskwiki#310]
Hi folks, I am following the install process but come up against the following:

git clone https://github.com/tools-life/taskwiki ~/.vim/bundle/taskwiki
Cloning into '/Users/rhaynes/.vim/bundle/taskwiki'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3749 (delta 0), reused 2 (delta 0), pack-reused 3745
Receiving objects: 100% (3749/3749), 1.15 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (2471/2471), done.

smatm0013:.vim:% git clone https://github.com/powerman/vim-plugin-AnsiEsc ~/.vim/bundle/
fatal: destination path '/Users/rhaynes/.vim/bundle' already exists and is not an empty directory.

**Comment by liskin** [comment]
Maybe don't try to clone `vim-plugin-AnsiEsc` (which is an entirely different vim plugin unrelated to taskwiki) into ~/.vim/bundle but into ~/.vim/bundle/vim-plugin-AnsiEsc instead?

**Comment by rhaynes74** [comment]
Many thanks!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
