### ISSUE TITLE
How taskwiki manage to use multiple tw db ?

### ISSUE THREAD

**Issue by sucrecacao** [tools-life/taskwiki#313]
How taskwiki manage to use multiple tw db and would it be possible to use this feature independently for another tool ?

**Comment by tbabej** [comment]
Taskwiki (using tasklib under the hood) instructs task to override the `data.location` configuration variable (see `man taskrc`). Hence you can point task to an alternative data location directly on the command line without any additional tools:

    task rc.data.location=/tmp/testlocation/ add Task saved in an alternate location

**Comment by sucrecacao** [comment]
I was more refereeing on how it can manage multiple dababase at *the same time*:
https://github.com/tbabej/taskwiki/blob/master/doc/taskwiki.txt#L443.

**Comment by tbabej** [comment]
We initialize a different `TaskWarrior` for each data location: https://github.com/tools-life/taskwiki/blob/a6907bac85f068f213272f51d2f2d77d67f72426/taskwiki/store.py#L23
