### ISSUE TITLE
<CR> should show preset header info

### ISSUE THREAD

**Issue by folofjc** [tools-life/taskwiki#321]
I left a comment about this [here](https://github.com/tools-life/taskwiki/issues/196#issuecomment-759713734). 

When the cursor is on a preset header, `<CR>` goes to vimwiki instead of taskwiki. It looks like the reason is around lines 284-291 of `taskwiki/main.py` where it only checks for tasks and viewports. It should also check for preset headers. Right now `:TaskWikiInspect` returns an error for preset headers, so first would need to populate this with some information before this will work.

Otherwise the only way to show the preset header info is to go into insert mode. This is problematic because you might not know whether what is under the cursor is a preset header or a viewport. 

What is even odder, is that if your cursor is under part of the hidden preset header, <CR> makes a link out of something hidden so you cannot even see what it does, and then it messes up the preset header.

**Comment by liskin** [comment]
A workaround might be to `let g:taskwiki_disable_concealcursor = 1`. This will reveal the conceals on current line without requiring you to enter insert mode. Though I agree that preset inspection would be a meaningful addition to https://github.com/tools-life/taskwiki/blob/72397a8c23fc793fb696f0c583248bae1dc4ceb4/taskwiki/main.py#L284-L291

**Comment by folofjc** [comment]
Thanks, I think that is a good workaround, and is what vimwiki does with links anyways.

**Comment by tbabej** [comment]
I believe this is now fixed thanks to @salman69e27 :slightly_smiling_face:

**Comment by folofjc** [comment]
Thanks!
