### ISSUE TITLE
Difficulties with installation instructions (beginner)

### ISSUE THREAD

**Issue by CreativeLibre** [tools-life/taskwiki#323]
As a relative newbie, I'm sorry to say that the installation instructions are absolutely poor. I unfortunately do not get it to run. In the current instruction so much is assumed and expected, but that does not apply to beginners. Is there somewhere a detailed tutorial on how I can install this package?

**Comment by tbabej** [comment]
Sorry you're having trouble! I agree the instructions are old-ish and maybe could use some polishing. In the meantime, is there a specific problem we can help you with?

**Comment by CreativeLibre** [comment]
Thanks for your answer. I will write the next few days all the problems I had during the installation together and report here.

**Comment by amagee** [comment]
I am not a beginner but I was also unable to get it to run.

Here's what I did:

- Installed taskwarrior v2.5.1 (`sudo apt install taskwarrior` on my Ubuntu machine)
- Installed vimwiki and taskwiki via Plug:

```
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
Plug 'tools-life/taskwiki'
```

- Installed the `develop` branch of the `tasklib` Python package into the Python virtual environment that's referred to in my `g:python_host_prog` and `g:python_3_host_prog` Neovim variables:

```
pyenv activate <my neovim python env>
git clone git@github.com:tbabej/tasklib.git
cd tasklib
git checkout develop
pip install -e .
```

I receive no error messages and the all the packages are installed (eg. `:help taskwiki` works) but the desired behaviour: "Such tasks get synced to TaskWarrior when the file is saved" does not occur.

Ie. if I open `~/.vimwiki/index.wiki` and enter

**Comment by amagee** [comment]
Update: I noticed there was a `requirements.txt` file in the taskwiki checkout itself, and installing from that instead of cloning the develop branch of `tasklib` made things work.
