### ISSUE TITLE
Viewports not being recognised

### ISSUE THREAD

**Issue by NoahFournier** [tools-life/taskwiki#324]
Having an issue with viewports not being recognised, and tasks therefore not inheriting attributes.

Here's an example which isn't recognised on my machine: 

`== Research Project | project:ResearchProject ==`

Viewport inspection doesn't work either, and they aren't recognised in my vim-tagbar.

Any idea as to what might be going on ? As far as I can tell, all other functionality except for preset headers and viewports works fine.

**Comment by tbabej** [comment]
Perhaps you have `markdown` syntax turned on, which would require you to write your viewports like this?

```
## Research Project | project:ResearchProject
```

**Comment by NoahFournier** [comment]
No I've got vimwiki syntax on, as is indicated by my airline bar.

Thanks for taking the time to answer !
