### ISSUE TITLE
taskwiki causes some vimwiki settings (relating to conceal) to change 

### ISSUE THREAD

**Issue by jmtd** [tools-life/taskwiki#325]
I've got vimwiki configured to be fairly minimal. I do not configure any "conceal" settings, so, in normal operation, a link `[[example]]` is rendered exactly like that.

When I load taskwiki, various concealments start happening. The following text

```
[[test]]
[[foo|bar]]
what `the` heck
ho *hum*
this _is_ annoying
```
renders like this:
> test
> bar
> what `the` heck
> ho *hum*
> this _is_ annoying

I haven't (yet) figured out which settings are being flipped, but `g:vimwiki_conceallevel` remains set to 0.

**Comment by tbabej** [comment]
Taskwiki is pretty opinionated about concealment, though it does not change vimwiki settings for concealment per se, just the normal vim settings:

https://github.com/tools-life/taskwiki/blob/a3ae9c52cdab4001be3471db8b28a19acdebb716/after/syntax/vimwiki.vim#L51-L56

**Comment by jmtd** [comment]
> Taskwiki is pretty opinionated about concealment, though it does not change vimwiki settings for concealment per se, just the normal vim settings:

Thanks that's exactly what I needed to know; it's `conceallevel` in particular that troubles me (I had pre-emptively headed off changes to `concealcursor` it seems by setting `g:taskwiki_disable_concealcursor` before first use).

I guess this could be considered a wishlist issue to not set `conceallevel`, in a similar way — perhaps that should actually ber inside that if block? As a workaround I'm going to try a hook on filetype to reset it (I'm not a particularly experienced vim scripter)
