### ISSUE TITLE
How to regenerate task's tags in Preset Headers?

### ISSUE THREAD

**Issue by Cloufish** [tools-life/taskwiki#337]
Suppose I've written down a bunch of new tasks,

But then I wanted to change the name of the tag that gets assigned to the task.
I change the name...

Then, I don't see task's tags being updated

Is there a way to regenerate them instead of rewritting every task?

**Comment by Cloufish** [comment]
If you manage all your tasks in vimwiki, you can delete contents of ~/.task directory - **Remember to take backup of them**

**Comment by Cloufish** [comment]
> If you manage all your tasks in vimwiki, you can delete contents of ~/.task directory - **Remember to take backup of them**

thanks

**Comment by tbabej** [comment]
Definitely! You can select all the tasks in the visual mode, and perform a group modification on them using `:TaskWikiMod -oldtag +newtag`
