### ISSUE TITLE
Not an editor command :TaskWiki*

### ISSUE THREAD

**Issue by bufordtaylor** [tools-life/taskwiki#339]
Hey folks,

Long time vimwiki user trying to get taskwiki setup but having a hard time. None of the :TaskWiki commands are woking within vim, and I'm not sure how to debug any further than what I've listed here. Does anyone know where else I can look?

I type in neovim
```
:TaskWikiTags

E492: Not an editor command: TaskWikiTags
Press ENTER or type command to continue
```

None of my tasks from the command line show up in vimwiki and vice versa.

Typing :help taskwiki works as shown
![image](https://user-images.githubusercontent.com/214319/118261233-479a2f80-b481-11eb-9659-efd453bc8123.png)

Typing :checkhealth'
```
health#mkdp#check
========================================================================
  - INFO: Platform: macos
  - INFO: Nvim Version: NVIM v0.4.4
  - INFO: Node version: v14.4.0
......
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.1
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

command line taskwarrior seems to work

```
{13:57}~/notes/vimwiki:master ✗ ➭ task
[task next]

ID Age   Tag  Description        Urg
 2 49min test test task with tag  0.8
 3 31min test test2               0.8
 1 59min      test task             0

3 tasks
```

Snippet of my `.config/nvim/init.vim`

```
call plug#begin("~/.config/nvim/plugged")
  Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
  Plug 'vimwiki/vimwiki'
  Plug 'tools-life/taskwiki'
call plug#end()

"vimwiki settings
let g:vimwiki_list = [
      \{
      \ 'path': '~/notes/vimwiki',
      \ 'path_html': '~/notes/vimwiki/html',
      \ 'diary_rel_path': './diary/',
      \ 'syntax': 'markdown',
      \ 'auto_tags': 1,
      \ 'auto_toc': 1,
      \ 'ext': '.md' },
      \]
let g:vimwiki_global_ext = 0
let g:vimwiki_auto_header = 1
let g:vimwiki_auto_chdir = 1
let g:vimwiki_markdown_link_ext = 1

let g:taskwiki_markdown_syntax = 'markdown'
```

**Comment by szaffarano** [comment]
Hi @bufordtaylor 
Perhaps my question is obvious, but are you running `:TaskWikiTags:` in a `VimWiki` buffer? Try going to any VimWiki page, for instance, press `<leader>ww` to go to the default wiki and run any `:TaskWiki*` command again.

**Comment by bufordtaylor** [comment]
Confirmed not working running `:TaskWikiTags:` in a vimwiki buffer, unfortunately. Still no dice.

**Comment by bufordtaylor** [comment]
I have solved this. Bone-headed mistake. For future people:

1. Install taskwiki via whatever plugin manager you use
2. Navigate to where it's installed e.g. ~/.config/nvim/plugged/taskwiki
3. `pip3 install --upgrade -r requirements.txt`. <---- this is the step I missed

I had not installed the `six` python package.

All is well. This can be closed now.
