### ISSUE TITLE
Introduce TaskWikiToggle command

### ISSUE THREAD

**Issue by fullstopslash** [tools-life/taskwiki#343]
We have TaskWikiStart and TaskWikiStop, but what about a TaskWikiToggle for a single command for starting and stopping tasks based on their current state? I'd love it!

**Comment by tbabej** [comment]
Sounds like a good addition. I'm wondering if you have any suggestions for the default keymap?

We can also not be so keybinding-hungry and not define any by default :thinking:

**Comment by fullstopslash** [comment]
<leader>tx seems reasonable to me for some reason, but I could be an outlier. <leader>tt being already taken by TaskWikiTags. <leader>tT may be the obvious choice as its another mnemonic for **t**askWiki**T**oggle

**Comment by fullstopslash** [comment]
> We can also not be so keybinding-hungry and not define any by default 🤔

I think perhaps that would be for the best. I feel like most people copy and paste the "recommended defaults" to their .rc anyway, so clobbering them with a bunch of already mapped keybindings seems like bad form. It seems like a convention that some of the other popular plugins use as well. Telescope for instance (correct me if I'm wrong here) doesn't set up default bindings, but has some suggested defaults in the Readme.

**Comment by tbabej** [comment]
@fullstopslash There is an open PR to implement this now on the `toggle-cmd` branch, perhaps you'd be willing to give it a test?

**Comment by fullstopslash** [comment]
Tried it out and it seems to be working fine on my end! Thanks so much!
