### ISSUE TITLE
Tabs result in strange indentation

### ISSUE THREAD

**Issue by mbanerjeepalmer** [tools-life/taskwiki#352]
When I use two or four spaces for indentation the dependencies are fine.
```
* [ ] Test parent  #d055e0e3
  * [ ] Test child 1  #ee11aa9f
  * [ ] Test child 2  #4a17caa2
```

But with tabs I end up with each indented depending on the one above it.

```
* [ ] Verify parent  #5f9016bb
	* [ ] Verify child 1  #e8fd734b
	* [ ] Verify child 2  #af536cb3
```

```
Name                  Value                               
ID                    15
Description           Verify child 1                      
Status                Pending
This task blocked by  14 Verify child 2                   
This task is blocking 16 Verify parent
```

It looks like this is the same problem as #167.

I'd be a bit surprised if TaskWiki didn't handle tabs. Searching the issue history and docs I can't see references to tabs. But maybe it's something else in my setup.

**Comment by tbabej** [comment]
I think this is a bug. Investigating now.

**Comment by tbabej** [comment]
@mbanerjeepalmer can you check if #353 fixes your issue?

**Comment by mbanerjeepalmer** [comment]
Lightning response!

Looks like it works. I'll keep stay on that branch for now and shout if it stops working.
