### ISSUE TITLE
Updating Diary index page removes all text

### ISSUE THREAD

**Issue by TeaWhyDee** [tools-life/taskwiki#354]
If I have taskwiki enabled, running :VimwikiDiaryGenerateLinks in the diary index page (diary.wiki) removes all text.
If I have taskwiki disabled, the command works as expected and generates the entry list.
Vimwiki settings are default.

**Comment by karlh626** [comment]
I have the same issue.

**Comment by jorgenriseth** [comment]
Had the same problem. It is seemingly related to folding, and I would not be surprised if changing the folding override mentioned in issue #147 would help.

I managed to get it working by commenting out lines 43-46 and 50 of `[taskwiki-folder]/ftplugin/vimwiki/taskwiki.vim`. Alternatively you can comment out only line 50, and add `let g:taskwiki_dont_preserve_folds='yes'`  to your `.vimrc`.

```vim
 38 augroup taskwiki
 39     autocmd! * <buffer>
 40     " Update to TW upon saving
 41     autocmd BufWrite <buffer> TaskWikiBufferSave
 42     " Save and load the view to preserve folding, if desired
 43     "if !exists('g:taskwiki_dont_preserve_folds')  <-- 
 44     "  autocmd BufWinLeave <buffer> call taskwiki#MkView() <--
 45     "  autocmd BufWinEnter <buffer> call taskwiki#LoadView() <--
 46     "endif <--
 47     " Reset cache when switching buffers
 48     execute "autocmd BufEnter <buffer> :" . g:taskwiki_py . "cache.load_current().           reset()"
 49     " Update window-local fold options
 50     "autocmd BufWinEnter <buffer> call taskwiki#FoldInit() <--
 51 
 52     " Refresh on load (if possible, after loadview to preserve folds)
 53     if has('patch-8.1.1113') || has('nvim-0.4.0')
 54       autocmd BufWinEnter <buffer> ++once TaskWikiBufferLoad
 55     else
 56       TaskWikiBufferLoad
 57     endif
 58 augroup END
```

For some reason it is possible to generate the diary index without this fix as long as you add `= Index =` as a header in the file. It will then generate a folded diary index. However, it will also change the header to `= Diary =` , meaning that the index will disappear at the  next attempt of generating links.

**Comment by TeaWhyDee** [comment]
FIX FOUND 
```
let g:taskwiki_dont_preserve_folds='yes'  
let g:taskwiki_dont_fold="yes"
```
In your vimrc, no source file editing required.
