### ISSUE TITLE
Taskwiki is overriding local foldmethod settings

### ISSUE THREAD

**Issue by sdondley** [tools-life/taskwiki#371]
I have the following in after/ftplugin/vimwiki.vim:

```
setlocal foldmethod=expr
setlocal foldenable 
set foldexpr=VimwikiFoldLevelCustom(v:lnum)
```

The foldmethod was getting ignored. I was forced to manually set the foldmethod from the command line.

It turns out the culprit was taskwiki, line 19, in `autoload/taskwiki.vim`

```
function! taskwiki#FoldInit() abort
  " Unless vimwiki is configured to use its folding, set our own
  if &foldtext !~? 'VimwikiFold'
    setlocal foldmethod=syntax   <-------------------- Line 19
    setlocal foldtext=taskwiki#FoldText()
  endif
endfunction
```

I think taskwiki is using a variable that is no longer used by vimwiki, `VimwikiFold`, to detect if  vimwiki has folding turned on.

Also see https://vi.stackexchange.com/questions/34745/foldmethod-setting-ignored-when-initializing-vim/34746#34746

**Comment by liskin** [comment]
Note that there's also https://github.com/tools-life/taskwiki/commit/5e125960c95de59c412954f1484ff667ba6bcf8f which may be useful in your case.

**Comment by sdondley** [comment]
OK, found the issue.

I initially put the `let g:taskwiki_dont_fold=1` line into `after/ftplugin/vimwiki`. After moving it to `~/.vimrc`, it appears to work.
