### ISSUE TITLE
Possible to change behavior of how metadata is hidden?

### ISSUE THREAD

**Issue by sdondley** [tools-life/taskwiki#380]
Taskwiki used to show the task meta data when the cursor was on the same line as the task or heading. Now, however, I have to go into insert mode to view the meta data. I don't see anything in the help file that indicates how this might be controlled.

Is there a way to restore the original behavior?

**Comment by liskin** [comment]
These seem related: https://github.com/tools-life/taskwiki/commit/67e5444cdf44c4ea23793e18a0e1421c2ab272a5, https://github.com/tools-life/taskwiki/issues/325#event-4547503098

Try `let g:taskwiki_disable_concealcursor = 1` in your vimrc.

**Comment by sdondley** [comment]
Perfect. Thanks. I wasn't searching the help file with the proper words.
