### ISSUE TITLE
Error detected while processing function provider#python3#Call

### ISSUE THREAD

**Issue by cmdln** [tools-life/taskwiki#388]
Upgraded to Pop_OS! 21.10. Using the nvim.appimage from the NeoVim official releases. NeoVim is version 0.5.0.

```bash
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Python 3.9.7

Vimwiki is current head of dev branch
```
commit 95dd2e0d2c7bc4a592941dd2cf474851bc345f15 (HEAD -> dev, origin/dev)
Author: Tulio Brunoro <tulio@brunoro.org>
Date:   Thu Nov 18 11:29:42 2021 -0300

    Revert breaking changes to customwiki2html.sh file

    There is an extra space when calling the `basename` command, which causes the following error:
    ```
    Vimwiki: 'basename: extra operand ‘md’
    Try ''basename --help'' for more information.
    ```
```
![Screenshot from 2021-12-16 20-03-05](https://user-images.githubusercontent.com/55718/146473710-2b3f312f-cb91-468f-90df-694ec99cddc3.png)

**Comment by tbabej** [comment]
@cmdln Thanks for the bug report! Any chance running `:messages` after this error shows up would display the last line? It looks like the actual error message is being overshadowed by vim's message about writing the file.

Also, just to make sure I have the correct environment when reproducing this - what is the `task --version` and `tasklib` version?

**Comment by cmdln** [comment]
`:messages` outputs the same text in the screenshot, there does not appear to be more to the error.

task is 2.5.3
tasklib is 2.4.3

The viewport in question uses `modified:`, I have sections in my diary entries to help show what was changed on a given day. I think that is the problem, I was adding a task in that viewport and saving. I think the error is write, taskwiki cannot update modified, it is read only. If I add a task to a viewport with the same filters *except* modified, it continues to work fine. I think my upgrade was a coincidence not the cause.

I am OK with closing this bug or if you want to change it to be about a better error message, trying to save a task to a viewport that uses an unmodifiable field; either way!

Thanks for the very fast response, by the way!

**Comment by tbabej** [comment]
I see, this all makes a lot of sense. Thanks for the clarification. So what's happenning under the hoot is indeed that with the following viewport:

```
### All the tasks modified today | modified:today
```

taskwiki uses `modified:today` both as the filter and default modifications for newly added tasks. However, the good news is that you can actually separate the filter from modifications if you provide two sections, like this:

```
### Tasks modified today where I can add tasks | modified:today | 
```

In this case the default modifications are empty, and the filter is modified:today. As a bonus, this works fine, because a newly added task does indeed match `modified:today` filter :slightly_smiling_face: 

Hope this helps!

**Comment by cmdln** [comment]
Ah, right! I remember that from the docs. I am still learning, I only started using taskwiki a few months ago. Nearly every day I keep finding new ways to use it in vimwiki.

By the way, taskwiki is fantastic! I've been using vimwiki and taskwarrior for years. A few months back I started feeling like there was something missing--taskwiki was it!
