### ISSUE TITLE
Do viewports *need* a project to work?

### ISSUE THREAD

**Issue by ryspace** [tools-life/taskwiki#421]
I'm just testing out TW, and task warrior, and I tried setting up a header as:

`== To Do | +PENDING ==`

However, my task(s) don't get pulled into my vimwiki (granted, there's currently only one task, but still) - Every implementation I see in all the issues I've browsed in here seem to mention a project in the viewport - is that a requirement? If it is, what if someone wants to list *all* of their pending tasks?

Sorry this is such a basic question. I promise I've read through a lot of old issues and the readme to try to figure it out myself.

---

**Edit:** I'm using default formatting for the wiki. The only thing I've changed about the default TaskWiki install is that I disabled folding in the config file for it with:

`let g:taskwiki_dont_fold = 'yes'`

**Edit 2:** Fix typo - "pending" was in all caps

**Comment by liskin** [comment]
Mentioning a project isn't a requirement. You're not seeing any tasks because your header literally asks for tasks tagged with the `Pending` tag, and you probably don't (want to) have any such tasks. Virtual tags are all uppercase, not just first uppercase rest lowercase. Perhaps you meant `+PENDING`?

**Comment by ryspace** [comment]
Sorry, that's a typo in my issue post...I did have `+PENDING`

**Comment by ryspace** [comment]
```
Name: All Tasks
Filter used: -DELETED -PARENT ( +PENDING )
Defaults used:
Ordering used: status+,end+,due+,priority-,project+
Matching taskwarrior tasks: 0
Displayed tasks: 0
Tasks to be added:
Tasks to be deleted:
```

Just to prove there's a task:

```
task

ID Age   Tag  Description                                                            Urg
 1 15h   nvim coc vim plugin sticking                                                 1.6
                2022-12-13 how to get out of suggestions without exiting insert mode

1 task
```

**Comment by ryspace** [comment]
Also, if I change +PENDING to +nvim, it still doesn't load the task.

**Comment by liskin** [comment]
It almost looks like it uses a completely separate taskwarrior database… or something.

**Comment by ryspace** [comment]
do I need to explicitly specify where my database is? It's not in the default location, but in `$XDG_DATA_HOME/task`...

Where would I specify that and how?

**Comment by ryspace** [comment]
I yanked and pasted the line directly from the help file, changed the directories to my own, and it's complaining that there's a missing comma in the dictionary...

**Comment by ryspace** [comment]
Figured it out....the help line is missing a `}` at the end, but the actual settings I wanted were

```
Plug 'tools-life/taskwiki'

let g:taskwiki_dont_fold = 'yes'
let g:taskwiki_taskrc_location = '~/.config/task/taskrc'
let g:taskwiki_data_location = '~/.local/share/task'
```
