### ISSUE TITLE
Show filter query on viewports in normal mode when the cursor is on them

### ISSUE THREAD

**Issue by LukeDAtkinson** [tools-life/taskwiki#431]
I find it a bit awkward to edit the filters on viewports.
I like to use normal mode to move around in the filter query. However in normal mode I cannot see the query or where I am in it.

This also made me think my h and l keys were somehow broken when I first started using taskwiki: if the cursor is in the filter query in normal mode, horizontal movement has no apparent effect, since it is moving within the hidden text. This is also the case if your cursor ends up in a task annotation in normal mode.

Would it be possible to show the filter query (and also annotations on tasks) when the cursor is on the viewport line, or within the filter query?

**Comment by Fabrice-Bernes** [comment]
Does it work as you'd expect if you run `:set concealcursor=` ?
If running `:set concealcursor` shows you a string with an `n`, then that's your problem. See `:help concealcursor`
